### ISSUE TITLE
Push配信が突然届かなくなる

### ISSUE THREAD

**Issue by LeoAndo** [plaidev/karte-tracker-android#1]
**問題現象**
アプリアンインストール＞インストール＞初回起動操作を行うと、
Push配信が突然届かなくなる。

**原因**
1端末に複数のKarteユーザIDが登録されてるためPush配信が突然届かなくなる

チェックリスト
https://support2.karte.io/app/karte-for-app-faq/9011/#user-id
11 同じユーザーに対して複数のuser_idを連携していないか　参照

**対策**
バックアップ設定ＯＦＦ（android:allowBackup="false"）する。
バックアップ設定ＯＮにすると、1端末に複数のKarteユーザIDが登録されてしまう。

**Comment by takaaki7** [comment]
https://github.com/plaidev/karte-tracker-android/pull/2 で修正済。対応ありがとうございます。
